sudo: required
services:
  - docker

before_install: 
  - docker build -t musabafzal/react-test -f ./mainclient/Dockerfile.dev ./mainclient

script:
  - docker run musabafzal/react-test npm run test -- --coverage

after_success:
  - docker build -t musabafzal/multi-client ./mainclient
  - docker build -t musabafzal/multi-nginx ./nginx
  - docker build -t musabafzal/multi-server ./server
  - docker build -t musabafzal/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push musabafzal/multi-client
  - docker push musabafzal/multi-nginx
  - docker push musabafzal/multi-server
  - docker push musabafzal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-518781601835"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

