sudo: required
services:
  - docker

before_install: 
  - docker build -t musabafzal/react-test -f ./mainclient/Dockerfile.dev ./mainclient

script:
  - docker run musabafzal/react-test npm run test -- --coverage

after_success:
  - docker build -t musabafzal/multi-client ./mainclient
  - docker build -t musabafzal/multi-nginx ./nginx
  - docker build -t musabafzal/multi-server ./server
  - docker build -t musabafzal/multi-worker ./worker
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  - docker push musabafzal/multi-client
  - docker push musabafzal/multi-nginx
  - docker push musabafzal/multi-server
  - docker push musabafzal/multi-worker

